api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

# Url Patterns

router = routers.DefaultRouter()
router.register(r'ideas', views.IdeaViewSet)
router.register(r'users', views.UserViewSet)
router.register(r'skills', views.SkillViewSet)
router.register(r'materials', views.MaterialViewSet)
router.register(r'work_types', views.WorkTypeViewSet)

urlpatterns = [
    path('', include(router.urls), name='api'),
    path('api-auth/', include(
        'rest_framework.urls', 
        namespace='rest_framework'
        )),
]

directory/urls.py
from django.urls import path
from . import views

app_name = 'directory'

urlpatterns = [
    path('', views.directory, name='directory'),
    path('users/', views.user_list_view, name='users'),
    path('users/<int:id>/', views.user_detail_view, name='user_detail'),
    path('ideas/', views.idea_list, name='ideas'),
    path('ideas/<slug:slug>/', views.idea_detail, name='idea_detail'),
    path('user-skills/<int:skill_id>', views.list_skills, name='user_skill'),
    path('user-materials/<int:material_id>', views.list_materials, name='user_material'),
    path('user-worktype/<int:type_id>', views.list_work_type, name='user_work_type'),
    path('idea-skills/<int:skill_id>', views.list_idea_skills, name='idea_skill'),
    path('idea-materials/<int:material_id>', views.list_idea_materials, name='idea_material'),
    path('idea-worktype/<int:type_id>', views.list_idea_work_type, name='idea_work_type'),
]

skid/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path
from users.views import Credits, HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', HomePage.as_view(), name='home'),
    path('credits/', Credits.as_view(), name='credits'),
    path('directory/', include('directory.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
    path('summernote/', include('django_summernote.urls')),
]

# Early method for serving media. If this was bigger production use AWS buckets
# or similar.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('add-skill/', views.add_skill, name='add_skill'),
    path('add-material/', views.add_material, name='add_material'),
    path('add-work-type/', views.add_work_type, name='add_work_type'),
    path('<int:id>/', views.profile, name='profile'),
    path('<int:id>/edit/', views.edit_profile, name='edit_profile'),
    path('<int:id>/create-idea/', views.create_idea, name='create_idea'),
    path('<int:id>/edit-idea/<slug:slug>', views.edit_idea, name='edit_idea'),
    path('<int:id>/delete-idea/<slug:slug>', views.delete_idea, name='delete_idea'),
    path('<int:id>/view-ideas/', views.view_ideas, name='view_ideas'),
    
]

users/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.contrib.auth import get_user_model
from django_summernote.widgets import SummernoteWidget

from .models import *

User=get_user_model()

# Forms

class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')
 
    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True)
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)

    class Meta: 
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

class ProfileUpdateForm(forms.ModelForm):

    phone_number = forms.CharField(max_length=31, required=False)

    class Meta:
        model = Profile
        widgets = {
            'about': SummernoteWidget(),
        }

        fields = [
            'business_name',
            'email_public',
            'phone_number',
            'address',
            'city',
            'state_province',
            'zip_code',
            'country',
            'about',
            'skills',
            'materials',
            'type_of_work',
        ]

        labels = {
            'type_of_work': 'Type of Work',
        }

class IdeaForm(forms.ModelForm):

    class Meta:
        model = Idea
        widgets = {
            'author': forms.HiddenInput(),
            'slug': forms.HiddenInput(),
            'text': SummernoteWidget(),
        }

        fields = [
            'author',
            'title',
            'slug',
            'text',
            'skills',
            'materials',
            'type_of_work',
            'status'
        ]


class SkillForm(forms.ModelForm):
    skill = forms.CharField(required=False)

    class Meta:
        model = Skill
        fields= ['skill']

class MaterialForm(forms.ModelForm):
    material = forms.CharField(required=False)

    class Meta:
        model = Material
        fields= ['material']

class WorkTypeForm(forms.ModelForm):
    work_type = forms.CharField(required=False)

    class Meta:
        model = WorkType
        fields= ['work_type']

class CommentForm(forms.ModelForm):
    
    text = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 4}),
        required=False, label=False
    )

    class Meta:
        model = Comment
        widgets = {
            'idea': forms.HiddenInput(),
            'commenter': forms.HiddenInput()
        }
        
        fields = [
            'idea', 
            'commenter', 
            'text',
        ]

     

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.forms.models import model_to_dict
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from .forms import *
from .models import Profile

User=get_user_model()

# BASE VIEWS

class HomePage(TemplateView):
    """Class based view diplays the SKID homepage."""
    template_name = 'home.html'

class Credits(TemplateView):
    """Class based view diplays the credits page."""
    template_name = 'credits.html'

# USER APP VIEWS

@login_required()
def profile(request, id):
    """View function displays user profile."""
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            profile = Profile.objects.filter(user_id__id=id).first()
            context = {
                'profile': profile,
                'user': user,
            }
            return render(request, 'users/profile.html', context)

        raise Exception("users/views.py profile()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')
        

@login_required()
def edit_profile(request, id):
    """
    View function displays form to edit user profile. Dynamically
    prepopulates the form with previously saved data.
    """
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            if request.method == 'POST':
                user_form = UserUpdateForm(request.POST, instance=request.user)
                profile_form = ProfileUpdateForm(request.POST, instance=request.user.profile)

                if user_form.is_valid() and profile_form.is_valid():
                    user_form.save()
                    profile_form.save()
                    messages.success(request, "Profile updated successfully.")
                
                    return redirect('users:profile', id)

                else:
                    messages.warning(request, "Please correct the error below.")

            elif request.method == 'GET':
                # Queries user's profile for existing data
                profile_data = Profile.objects.filter(user_id__id=id).first()
                # Converts data into dict to be passed the initial field
                existing_data = model_to_dict(profile_data)

                user_form = UserUpdateForm(instance=request.user)
                profile_form = ProfileUpdateForm(instance=user, initial=existing_data)

                context = {
                    'user_form': user_form,
                    'profile_form': profile_form,
                }
                return render(request, 'users/edit_profile.html', context=context)

        raise Exception("users/views.py edit_profile()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def create_idea(request, id):
    """
    View function displays form for user to create Idea. Prepopulates 
    'author' field to connect Idea to user.
    """
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            if request.method == 'POST':
                form = IdeaForm(request.POST)
                if form.is_valid():
                    form.save()
                    messages.success(request, 'Idea created successfully.')
                    
                    return redirect('users:profile', id)

                else:
                    print(form.errors)

            elif request.method == 'GET':
                author_field = {'author': user}
                form = IdeaForm(instance=user, initial=author_field)
              
                context = {
                    'form': form
                }
                return render(request, 'users/create_idea.html', context=context)

        raise Exception("users/views.py create_idea()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def edit_idea(request, id, slug):
    """
    View function displays form to edit Idea. Dynamically prepopulates form
    with previously saved data.
    """
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            # Queries idea for existing data
            idea_data = Idea.objects.filter(slug=slug).first()

            if request.method == 'POST':
                form = IdeaForm(request.POST, instance=idea_data)
                if form.is_valid():
                    form.save()
                    messages.success(request, 'Idea edited successfully.')

                return redirect('users:view_ideas', id)

            elif request.method == 'GET':
                # Converts data into dict to be passed the initial field
                existing_data = model_to_dict(idea_data)
                idea_form = IdeaForm(instance=user, initial=existing_data)

                context = {
                    'idea_form': idea_form
                    }

                return render(request, 'users/edit_idea.html', context=context)
        
        raise Exception("users/views.py edit_idea()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def delete_idea(request, id, slug):
    """View function displays form to allow user to delete Idea."""
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            # Queries idea for existing data
            idea_data = Idea.objects.filter(slug=slug).first()

            if request.method == 'POST':
                idea_data.delete()
                messages.success(request, 'Idea deleted successfully.')

                return redirect('users:view_ideas', id)

            elif request.method == 'GET':
                context = {'idea_data': idea_data}
                
                return render(request, 'users/delete_idea.html', context)
        
        raise Exception("users/views.py delete_idea()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def view_ideas(request, id):
    """View function displays table of users Ideas."""
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            ideas = Idea.objects.filter(author=user)
            context = {
                'ideas': ideas,
            }
            return render(request, 'users/view_ideas.html', context=context)

        raise Exception("users/views.py view_ideas()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def add_skill(request):
    """View function displays form for user to add Skill to table of skills."""
    try:
        skills = Skill.objects.all().order_by('skill')
        form = SkillForm(request.POST)

        if request.method == 'POST':
            if form.is_valid():
                instance = form.save(commit=False)
                if instance.skill == '':
                    messages.warning(request, 'Skill cannot be empty.')
                else:
                    instance.save()
                    messages.success(request, 'Skill added.')

            return redirect('users:add_skill')

        elif request.method == 'GET':
            context = {
                'skills': skills,
                'form': form,
            }

            return render(request, 'users/add_skill.html', context=context)
        
        raise Exception("users/views.py add_skill()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def add_material(request):
    """
    View function displays form for user to add Material to table of materials.
    """
    try:
        materials = Material.objects.all().order_by('material')
        form = MaterialForm(request.POST)

        if request.method == 'POST':
            if form.is_valid():
                instance = form.save(commit=False)
                if instance.material == '':
                    messages.warning(request, 'Material cannot be empty.')
                else:
                    instance.save()
                    messages.success(request, 'Material added.')

            return redirect('users:add_material')

        elif request.method == 'GET':
            context = {
                'materials': materials,
                'form': form,
            }

            return render(request, 'users/add_material.html', context=context)

users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
      <title>SKID | Skills x Ideas</title>
    {% endblock title %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" 
      rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" 
      crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="header">  
{% block navbar %}
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">SKID</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav">
        <a class="nav-link" aria-current="page" href="{% url 'directory:directory' %}">Directory</a>
        <a class="nav-link" aria-current="page" href="{% url 'directory:users' %}">Users</a>
        <a class="nav-link" aria-current="page" href="{% url 'directory:ideas' %}">Ideas</a>
        <a class="nav-link" aria-current="page" href="/api">API</a>
      </div>
      <div class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
          <a id="id_nav_user" class="nav-link" href="{% url 'users:profile' user.id %}">{{ user }} <img class="icon" src="{% static 'images/user.png' %}" alt=""></a>
          <a id="id_nav_logout" class="nav-link" href="{% url 'account_logout' %}">Log out <img class="icon" src="{% static 'images/logout.png' %}" alt=""></a>
        {% else %}
          <a id="id_nav_signup" class="nav-item nav-link" href="{% url 'account_signup' %}">Sign up <img class="icon" src="{% static 'images/signup.png' %}" alt=""></a>
          <a id="id_nav_login" class="nav-item nav-link" href="{% url 'account_login' %}">Log in <img class="icon" src="{% static 'images/login.png' %}" alt=""></a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>
<div class="spacer"></div>
{% endblock navbar %}
</div>

{% if messages %}
		<div class="messages">
		{% for message in messages %}
			<div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
				{{ message }}
			</div>
		{% endfor %}
		</div>
{% endif %}

<div class="content-wrap">
{% block content %}
    
{% endblock content %}
</div>

<div class="footer">
{% block footer %}
<div class="container">
  <footer class="mt-auto py-3 bg-grey">
    <p class="m-0 text-dark text-end small">Copyright &copy; <a href="https://www.josephmadsen.com">Joseph Madsen</a></p>
    <p class="m-0 text-dark text-end small"><a href="{% url 'credits' %}">Credits</a></p>
  </footer>
</div>
{% endblock footer %}
</div>

{% block scripts %}
  
{% endblock scripts %}
  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" 
  integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" 
  crossorigin="anonymous">
</script>

</body>
</html>

users/templates/credits.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1>Credits:</h1>
    <h2>ICONS</h2>
    <ul>
        <li>
            <a target="_blank" href="https://icons8.com/icon/IVlCJgXg1RYx/add-user-male">Add User</a>    
                icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        </li>
        <li>
            <a target="_blank" href="https://icons8.com/icon/24336/login-rounded">Login</a> 
                icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        </li>
        <li>
            <a target="_blank" href="https://icons8.com/icon/GbzCtg4y2X3X/log-out">Log Out</a> 
                icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        </li>
        <li>
            <a target="_blank" href="https://icons8.com/icon/ckaioC1qqwCu/male-user">User</a> 
                icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        </li>
    </ul>
    <h2>BACKGROUND PHOTOS</h2>
    <ul>
        <li>
            Photo by <a href="https://unsplash.com/@momentance?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">SwapnIl Dwivedi</a> 
            on <a href="https://unsplash.com/s/photos/craft?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
        </li>
        <li>
            Photo by <a href="https://unsplash.com/@austin__ramsey?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Austin Ramsey</a> 
            on <a href="https://unsplash.com/s/photos/craft?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
        </li>
        <li>
            Photo by <a href="https://unsplash.com/@nickkarvounis?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Nick Karvounis</a> 
            on <a href="https://unsplash.com/s/photos/craft?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
        </li>
        <li>
            Photo by <a href="https://unsplash.com/@eliomendes?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Elio Santos</a> 
            on <a href="https://unsplash.com/s/photos/craft?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
        </li>
        <li>
            Photo by <a href="https://unsplash.com/@cytonn_photography?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Cytonn Photography</a> 
            on <a href="https://unsplash.com/s/photos/typing?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
        </li>
        <li>
            Photo by <a href="https://unsplash.com/@jonathanbean?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jonathan Bean</a> 
            on <a href="https://unsplash.com/s/photos/blacksmith?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
        </li>
    </ul>
</div>
{% endblock content %}
    

users/templates/error_page.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1>Something Went Wrong</h1>
    
    {% if user.is_authenticated %}
        <p>It's not you, it's me . . .</p>
    {% else %}
        <P>Please log in to your account and try again.</P>
    {% endif %}
        
    <p></p>
    <a class="btn btn-primary" href="{% url 'home' %}">Return Home</a>
</div>
{% endblock content %}

users/templates/home.html
{% extends 'base.html' %}


{% block content %}
<div class="text-white" style="background-image: url('static/images/skid_background.png'); background-repeat: no-repeat;">
    <div class="text-center ">
        <div class="spacer"></div>
        <h1>Welcome to SKID</h1>
        <h2>Where Skills and Ideas Connect</h2>
        <div class="spacer"></div>
    </div>
    <div class="bckgrnd-opacity">
        <h5>OUR MISSION</h5>
        <div class="spacer"></div>
        <div class="container">
            <p>
                The goal of SKID is to faciliate the free flow of creativity and collaboration among our users. 
                No matter what skills or ideas you have, SKID is the place to find like-minded people.
            </p>
        </div>
        <div style="min-height: 30px;"></div>
        <h5>GETTING STARTED</h5>
        <div class="spacer"></div>
        <ol>
            <li>Sign up with username and password
                <a class="btn btn-outline-primary" style="margin-left: 20px;" href="{% url 'account_signup' %}">SIGN UP</a><br><br>
            </li>
            <li>Browse the directory of Users or Ideas 
                <a class="btn btn-outline-primary" style="margin-left: 20px;" href="{% url 'directory:users' %}">USERS</a>
                <a class="btn btn-outline-primary" style="margin-left: 20px;" href="{% url 'directory:ideas' %}">IDEAS</a><br><br>
            </li>
            <li>Connect and create!</li>
        </ol> 
    </div>
    <div style="min-height: 500px;"></div>
</div>
{% endblock content %}
    