api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

# Url Patterns

router = routers.DefaultRouter()
router.register(r'ideas', views.IdeaViewSet)
router.register(r'users', views.UserViewSet)
router.register(r'skills', views.SkillViewSet)
router.register(r'materials', views.MaterialViewSet)
router.register(r'work_types', views.WorkTypeViewSet)

urlpatterns = [
    path('', include(router.urls), name='api'),
    path('api-auth/', include(
        'rest_framework.urls', 
        namespace='rest_framework'
        )),
]

directory/urls.py
from django.urls import path
from . import views

app_name = 'directory'

urlpatterns = [
    path('', views.directory, name='directory'),
    path('users/', views.user_list_view, name='users'),
    path('users/<int:id>/', views.user_detail_view, name='user_detail'),
    path('ideas/', views.idea_list, name='ideas'),
    path('ideas/<slug:slug>/', views.idea_detail, name='idea_detail'),
    path('user-skills/<int:skill_id>', views.list_skills, name='user_skill'),
    path('user-materials/<int:material_id>', views.list_materials, name='user_material'),
    path('user-worktype/<int:type_id>', views.list_work_type, name='user_work_type'),
    path('idea-skills/<int:skill_id>', views.list_idea_skills, name='idea_skill'),
    path('idea-materials/<int:material_id>', views.list_idea_materials, name='idea_material'),
    path('idea-worktype/<int:type_id>', views.list_idea_work_type, name='idea_work_type'),
]

skid/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path
from users.views import Credits, HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', HomePage.as_view(), name='home'),
    path('credits/', Credits.as_view(), name='credits'),
    path('directory/', include('directory.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
    path('summernote/', include('django_summernote.urls')),
]

# Early method for serving media. If this was bigger production use AWS buckets
# or similar.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

directory/models.py
from django.db import models

# Create your models here.

directory/views.py
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect

from users.models import Idea, Profile, Skill, Material, WorkType
from users.forms import CommentForm

User=get_user_model()

# Create your views here.
 
def directory(request):
    """
    View function landing page for the directory side of the site.
    Lists links to filter users and ideas.
    """
    try:
        skills = Skill.objects.all().order_by('skill')
        materials = Material.objects.all().order_by('material')
        worktype = WorkType.objects.all().order_by('work_type')
        context = {
            'skills': skills,
            'materials': materials,
            'worktype': worktype,
        }
        return render(request, 'directory/directory.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')

#USER LIST AND DETAIL

def user_list_view(request):
    """View function lists all non-staff users and paginates results."""
    try:
        all_users = User.objects.filter(is_staff=False).order_by('last_name')
        paginator = Paginator(all_users, 5)
        page_number = request.GET.get('page')

        users = paginator.get_page(page_number)

        context = {
            'users': users,
        }
        return render(request, 'directory/user_list.html', context)

    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')

def user_detail_view(request, id):
    """View function diplays details of user."""
    try: 
        profile = Profile.objects.filter(user_id__id=id).first()
        context = {
            'profile': profile,
        }
        return render(request, 'directory/user_detail.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')

def list_skills(request, skill_id):
    """View function lists users by the skills they are tagged with."""
    try:
        skill = get_object_or_404(Skill, id=skill_id)
        all_users = skill.profile.all()
        paginator = Paginator(all_users, 5)
        page_number = request.GET.get('page')

        users = paginator.get_page(page_number)

        context = {
            'skill_name': skill.skill,
            'users': users,
        }
        return render(request, 'directory/user_list.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')

def list_materials(request, material_id):
    """View function lists users by the materials they are tagged with."""
    try: 
        material = get_object_or_404(Material, id=material_id)
        all_users = material.profile.all()
        paginator = Paginator(all_users, 5)
        page_number = request.GET.get('page')

        users = paginator.get_page(page_number)

        context = {
            'material_name': material.material,
            'users': users
        }
        return render(request, 'directory/user_list.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')

def list_work_type(request, type_id):
    """View function lists users by the type of work they are tagged with."""
    try:
        type = get_object_or_404(WorkType, id=type_id)
        all_users = type.profile.all()
        paginator = Paginator(all_users, 5)
        page_number = request.GET.get('page')

        users = paginator.get_page(page_number)

        context = {
            'type_name': type.work_type,
            'users': users
        }
        return render(request, 'directory/user_list.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


#IDEA LIST, DETAIL, AND COMMENT

def idea_list(request):
    """View function lists all ideas and paginates results."""
    try:
        all_ideas = Idea.objects.filter(status='p').order_by('-published')
        paginator = Paginator(all_ideas, 5)
        page_number = request.GET.get('page')

        idea_list = paginator.get_page(page_number)

        context = {
            'idea_list': idea_list
        }
        return render(request, 'directory/idea_list.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')

def idea_detail(request, slug):
    """View function displays details of ideas."""
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()
        
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Comment posted successfully.')
                
                return redirect('directory:idea_detail', slug)

        elif request.method == 'GET':
            idea = Idea.objects.get(slug=slug)
            comments = idea.comments.all()

            comment_fields = {'idea': idea, 'commenter': user}
            form = CommentForm(instance=user, initial=comment_fields)

            context = {
            'idea': idea,
            'comments': comments,
            'form': form,
            }   
            return render(request, 'directory/idea_detail.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')

def list_idea_skills(request, skill_id):
    """View function lists ideas by the skills they are tagged with."""
    try:
        skill = get_object_or_404(Skill, id=skill_id)
        all_ideas = skill.idea.all()
        paginator = Paginator(all_ideas, 5)
        page_number = request.GET.get('page')

        idea_list = paginator.get_page(page_number)
        
        context = {
            'skill_name': skill.skill,
            'idea_list': idea_list,
        }
        return render(request, 'directory/idea_list.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}

def list_idea_materials(request, material_id):
    """View function lists ideas by the materials they are tagged with."""
    try:
        material = get_object_or_404(Material, id=material_id)
        all_ideas = material.idea.all()
        paginator = Paginator(all_ideas, 5)
        page_number = request.GET.get('page')

        idea_list = paginator.get_page(page_number)

        context = {
            'material_name': material.material,
            'idea_list': idea_list
        }
        return render(request, 'directory/idea_list.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
    

def list_idea_work_type(request, type_id):
    """View function lists ideas by the type of work they are tagged with."""
    try:
        type = get_object_or_404(WorkType, id=type_id)
        all_ideas = type.idea.all()
        paginator = Paginator(all_ideas, 5)
        page_number = request.GET.get('page')

        idea_list = paginator.get_page(page_number)

        context = {
            'type_name': type.work_type,
            'idea_list': idea_list
        }
        return render(request, 'directory/idea_list.html', context)
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
    

directory/templates/directory/directory.html
{% extends 'base.html' %}


{% block title %}
    <title>SKID | Directory</title>
{% endblock title %}
    
{% block content %}
    <div class="container">
        <h1>The SKID Directory</h1>
        <div class="row justify-content-evenly">
            <div class="col-6">
                <div>
                    <h2>
                        See <a href="{% url 'directory:users' %}" style="text-decoration: none;">All Users</a>
                    </h2>
                </div>
                <div class="container">
                    <h3>List Users By:</h3>
                        <div class="container">
                            <h5>Skill</h5>
                                {% for skill in skills %}
                                    <a href="{% url 'directory:user_skill' skill.id %}" 
                                        class="badge bg-primary" style="text-decoration: none;">
                                        {{ skill }}
                                    </a>
                                {% endfor %}
                            <h5>Material</h5>
                                {% for material in materials %}
                                    <a href="{% url 'directory:user_material' material.id %}" 
                                        class="badge bg-primary" style="text-decoration: none;">
                                        {{ material }}
                                    </a>
                                {% endfor %}
                            <h5>Type of Work</h5>
                                {% for type in worktype %}
                                    <a href="{% url 'directory:user_work_type' type.id %}" 
                                        class="badge bg-primary" style="text-decoration: none;">
                                        {{ type }}
                                    </a>
                                {% endfor %}
                        </div>
                </div>
            </div>
        
            <div class="col-6">
                <div>
                    <h2>
                        See <a href="{% url 'directory:ideas' %}" style="text-decoration: none;">All Ideas</a>
                    </h2>   
                </div>
                <div class="container">
                    <h3>List Ideas By:</h3>
                        <div class="container">
                            <h5>Skill</h5>
                                {% for skill in skills %}
                                    <a href="{% url 'directory:user_skill' skill.id %}" 
                                        class="badge bg-primary" style="text-decoration: none;">
                                        {{ skill }}
                                    </a>
                                {% endfor %}
                            <h5>Material</h5>
                                {% for material in materials %}
                                    <a href="{% url 'directory:user_material' material.id %}" 
                                        class="badge bg-primary" style="text-decoration: none;">
                                        {{ material }}
                                    </a>
                                {% endfor %}
                            <h5>Type of Work</h5>
                                {% for type in worktype %}
                                    <a href="{% url 'directory:user_work_type' type.id %}" 
                                        class="badge bg-primary" style="text-decoration: none;">
                                        {{ type }}
                                    </a>
                                {% endfor %}
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
    

directory/templates/directory/idea_detail.html
{% extends 'base.html' %}


{% block content %}

{% load crispy_forms_tags %}

{% if user.is_authenticated %}
    <div class="container">
        <h3>{{ idea.title }}</h3>
        <h5 class="text-muted">by, <a href="{% url 'directory:user_detail' idea.author.id %}" 
            style="text-decoration: none;">{{ idea.author }}</a>
        </h5>
        
        <div class="container">
            Skills:
            {% for skill in idea.skills.all %}
                <a href="{% url 'directory:idea_skill' skill.id %}" 
                    class="badge bg-primary" style="text-decoration: none;">
                {{ skill }}
                </a>
            {% endfor %}
            <br>
            Materials:
            {% for material in idea.materials.all %}
                <a href="{% url 'directory:idea_material' material.id %}" 
                    class="badge bg-primary" style="text-decoration: none;">
                {{ material }}
                </a>
            {% endfor %}
            <br>
            Type of Work:
            {% for type in idea.type_of_work.all %}
                <a href="{% url 'directory:idea_work_type' type.id %}" 
                    class="badge bg-primary" style="text-decoration: none;">
                {{ type }}
                </a>
            {% endfor %}
        </div>

        <div class="spacer"></div>
        <p class="text-muted small">Published: {{ idea.published }} | Updated: {{ idea.updated }}</p>
        <div class="border-bottom mb-4"></div>

        <p class="word-wrap" style="width: 80rem;"> {{ idea.text | safe }}</p>
        <div class="spacer"></div>
        <a href="{% url 'directory:ideas' %}" class="btn btn-primary">Go Back</a>
        <div class="spacer"></div>

        
        {% if comments %}
        <div class="container">
            <div class="col-md-8 card mb-4 mt-3">
                <div class="card-body">
                <h4 class="">COMMENTS ({{ comments.count }})</h4>
                {% for comment in comments %}
                <div style="padding: 5px;">
                    <div class="card">
                        <div class="card-header">
                            <a href="{% url 'directory:user_detail' comment.commenter.id %}" 
                            style="text-decoration: none;">{{ comment.commenter }}</a>
                        <span class="text-muted small">{{ comment.created_on }}</span>
                        </div>
                        <div class="card-text" style="padding: 5px 0px 0px 10px;">
                        {{ comment.text | linebreaks }}
                        </div>
                    </div>
                </div>
                {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}
            
        <div class="container">
            <div class="col-md-8 card mb-4 mt-3">
                <div class="card-body">
                <h4>Leave a Comment</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input class="btn btn-primary" type="submit" value="Post">
                </form>
                </div>
            </div>
        </div>
    </div>
    
{% else %}
    <div class="container">
        <h5>Must be logged in to view this page.</h5>
    </div>
{% endif %}
    

{% endblock content %}
    

directory/templates/directory/idea_list.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1>Directory of Ideas</h1>

    {% if skill_name %}
    <div class="container">
        <h2>Skill: {{ skill_name }}</h2>

        {% for idea in idea_list %}
            <h4>
                <a href="{{ idea.get_absolute_url }}" style="text-decoration: none;">
                    {{ idea.title }}</a>, by {{ idea.author }}
            </h4>
        {% endfor %}
    </div>

    {% elif material_name %}
    <div class="container">
        <h2>Material: {{ material_name }}</h2>
        
        {% for idea in idea_list %}
            <h4>
                <a href="{{ idea.get_absolute_url }}" style="text-decoration: none;">
                    {{ idea.title }}</a>, by {{ idea.author }}
            </h4>
        {% endfor %}
    </div>

    {% elif type_name %}
    <div class="container">
        <h2>Type of Work: {{ type_name }}</h2>

        {% for idea in idea_list %}
            <h4>
                <a href="{{ idea.get_absolute_url }}" style="text-decoration: none;">
                    {{ idea.title }}</a>, by {{ idea.author }}
            </h4>
        {% endfor %}
    </div>
    
    {% else %}
        <h2>All Ideas</h2>
        <div class="container">
            {% for idea in idea_list %}
            <div class="card" style="width: auto; max-width: 50rem;">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{{ idea.get_absolute_url }}" style="text-decoration: none;">
                            {{ idea.title }}
                        </a>
                    </h5>
                    <h6 class="card-subtitle mb-2 text-muted">by {{ idea.author }}</h6>
    
                    <p class="card-text">{{ idea.text | safe | truncatechars:50 }}</p>
                    <ul style="list-style-type:none;">
                        <li>
                            Skills:
                            {% for skill in idea.skills.all %} 
                            <a href="{% url 'directory:idea_skill' skill.id %}" 
                                class="badge bg-primary" style="text-decoration: none;">
                                {{ skill }}
                            </a> 
                            {% endfor %}
                        </li>
                        <li>
                            Materials:
                            {% for material in idea.materials.all %}
                            <a href="{% url 'directory:idea_material' material.id %}" 
                                class="badge bg-primary" style="text-decoration: none;">
                                {{ material }}
                            </a>
                            {% endfor %}
                        </li>
                        <li>
                            Type of Work:
                            {% for type in idea.type_of_work.all %}
                            <a href="{% url 'directory:idea_work_type' type.id %}" 
                                class="badge bg-primary" style="text-decoration: none;">
                                {{ type }}
                            </a>
                            {% endfor %}
                        </li>
                    </ul>
                </div>
            </div>
            <div class="spacer"></div>
            {% endfor %}
        </div>
    {% endif %}
</div>

<!-- Pagination -->
<div class="pagination container">
    <span class="step-links">
        {% if idea_list.has_previous %}
            <a class="btn btn-primary btn-sm" href="?page=1">&laquo; first</a>
            <a class="btn btn-primary btn-sm" href="?page={{ idea_list.previous_page_number }}">previous</a>
        {% endif %}
  
        <span class="current text-muted">
            Page {{ idea_list.number }} of {{ idea_list.paginator.num_pages }}
        </span>
  
        {% if idea_list.has_next %}
            <a class="btn btn-primary btn-sm" href="?page={{ idea_list.next_page_number }}">next</a>
            <a class="btn btn-primary btn-sm" href="?page={{ idea_list.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>

{% endblock content %}

directory/templates/directory/user_detail.html
{% extends 'base.html' %}


{% block content %}

{% if user.is_authenticated %}
    <div class="container">
        <h1>{{ profile.user_id.first_name }} {{ profile.user_id.last_name }}</h1>
        <div class="container">
            Skills:
            {% for skill in profile.skills.all %} 
            <a href="{% url 'directory:user_skill' skill.id %}" 
                class="badge bg-primary" style="text-decoration: none;">
                {{ skill }}
            </a>
            {% endfor %}
            <br>      
            Materials:
            {% for material in profile.materials.all %}
            <a href="{% url 'directory:user_material' material.id %}" 
                class="badge bg-primary" style="text-decoration: none;">
                {{ material }}
            </a>
            {% endfor %}
            <br>    
            Type of Work:
            {% for type in profile.type_of_work.all %}
            <a href="{% url 'directory:user_work_type' type.id %}" 
                class="badge bg-primary" style="text-decoration: none;">
                {{ type }}
            </a>
            {% endfor %}
        </div>
        <div class="spacer"></div>
        <div class="spacer"></div>
        <div class="border-bottom mb-4"></div>

        <div class="container"> {{ profile.about | safe }}</div>

        <div class="spacer"></div>
        <div class="border-bottom mb-4"></div>

        <h3>Contact Information</h3>

        <ul style="list-style-type:none;">
            <li>Business Name: {{ profile.business_name }}</li>
            <li>Email: {{ profile.email_public }}</li>
            <li>Phone: {{ profile.phone_number }}</li>
            <li>
                Address:<br>
                {{ profile.address }}<br>
                {{ profile.state_province }}<br> 
                {{ profile.city }}<br>
                {{ profile.zip_code }}
                {{ profile.country }}<br>
            </li>
        </ul>
    </div>
    
{% else %}
    <div class="container">
        <h5>Must be logged in to view this page.</h5>
    </div>
{% endif %}
    

{% endblock content %}
    

directory/templates/directory/user_list.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1>Directory of Users</h1>

    {% if skill_name %}
    <div class="container">
        <h2>Skill: {{ skill_name }}</h2>

        {% for user in users %}
            <h4>
                {% if user.business_name %}
                    <a href="{% url 'directory:user_detail' user.user_id.id %}" style="text-decoration: none;">
                        {{ user.business_name }}
                    </a>
                {% else %}
                    <a href="{% url 'directory:user_detail' user.user_id.id %}" style="text-decoration: none;">
                        {{ user.user_id.last_name }}, {{ user.user_id.first_name }}
                    </a>
                {% endif %}
            </h4>
        {% endfor %}
    </div>

    {% elif material_name %}
    <div class="container">
        <h2>Material: {{ material_name }}</h2>
        
        {% for user in users %}
            <h4>
                {% if user.business_name %}
                    <a href="{% url 'directory:user_detail' user.user_id.id %}" style="text-decoration: none;">
                        {{ user.business_name }}
                    </a>
                {% else %}
                    <a href="{% url 'directory:user_detail' user.user_id.id %}" style="text-decoration: none;">
                        {{ user.user_id.last_name }}, {{ user.user_id.first_name }}
                    </a>
                {% endif %}
            </h4>
        {% endfor %}
    </div>
        
    {% elif type_name %}
    <div class="container">
        <h2>Type of Work: {{ type_name }}</h2>

        {% for user in users %}
            <h4>
                {% if user.business_name %}
                    <a href="{% url 'directory:user_detail' user.user_id.id %}" style="text-decoration: none;">
                        {{ user.business_name }}
                    </a>
                {% else %}
                    <a href="{% url 'directory:user_detail' user.user_id.id %}" style="text-decoration: none;">
                        {{ user.user_id.last_name }}, {{ user.user_id.first_name }}
                    </a>
                {% endif %}
            </h4>
        {% endfor %}
    </div>

    {% else %}
        <h2>All Users</h2>
        <div class="container">
            {% for user in users %}
                <div class="card" style="width: auto; max-width: 50rem;">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url 'directory:user_detail' user.id %}" style="text-decoration: none;">
                                {{ user.last_name }}, {{ user.first_name }}
                            </a>
                        </h5>
                        {% if user.profile.business_name %}
                        <h6 class="card-subtitle mb-2 text-muted">{{ user.profile.business_name }}</h6>
                        {%  endif %}
                        <ul style="list-style-type:none;">
                            <li>
                                Skills:
                                {% for skill in user.profile.skills.all %} 
                                <a href="{% url 'directory:user_skill' skill.id %}" 
                                    class="badge bg-primary" style="text-decoration: none;">
                                    {{ skill }}
                                </a> 
                                {% endfor %}
                            </li>
                            <li>
                                Materials:
                                {% for material in user.profile.materials.all %}
                                <a href="{% url 'directory:user_material' material.id %}" 
                                    class="badge bg-primary" style="text-decoration: none;">
                                    {{ material }}
                                </a>
                                {% endfor %}
                            </li>
                            <li>
                                Type of Work:
                                {% for type in user.profile.type_of_work.all %}
                                <a href="{% url 'directory:user_work_type' type.id %}" 
                                class="badge bg-primary" style="text-decoration: none;">
                                {{ type }}
                            </a>
                                {% endfor %}
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="spacer"></div>
            {% endfor %}
        </div>
    {% endif %}
</div>

<!-- Pagination -->
<div class="pagination container">
    <span class="step-links">
        {% if users.has_previous %}
            <a class="btn btn-primary btn-sm" href="?page=1">&laquo; first</a>
            <a class="btn btn-primary btn-sm" href="?page={{ users.previous_page_number }}">previous</a>
        {% endif %}
  
        <span class="current text-muted">
            Page {{ users.number }} of {{ users.paginator.num_pages }}
        </span>
  
        {% if users.has_next %}
            <a class="btn btn-primary btn-sm" href="?page={{ users.next_page_number }}">next</a>
            <a class="btn btn-primary btn-sm" href="?page={{ users.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>

{% endblock content %}