api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

# Url Patterns

router = routers.DefaultRouter()
router.register(r'ideas', views.IdeaViewSet)
router.register(r'users', views.UserViewSet)
router.register(r'skills', views.SkillViewSet)
router.register(r'materials', views.MaterialViewSet)
router.register(r'work_types', views.WorkTypeViewSet)

urlpatterns = [
    path('', include(router.urls), name='api'),
    path('api-auth/', include(
        'rest_framework.urls', 
        namespace='rest_framework'
        )),
]

directory/urls.py
from django.urls import path
from . import views

app_name = 'directory'

urlpatterns = [
    path('', views.directory, name='directory'),
    path('users/', views.user_list_view, name='users'),
    path('users/<int:id>/', views.user_detail_view, name='user_detail'),
    path('ideas/', views.idea_list, name='ideas'),
    path('ideas/<slug:slug>/', views.idea_detail, name='idea_detail'),
    path('user-skills/<int:skill_id>', views.list_skills, name='user_skill'),
    path('user-materials/<int:material_id>', views.list_materials, name='user_material'),
    path('user-worktype/<int:type_id>', views.list_work_type, name='user_work_type'),
    path('idea-skills/<int:skill_id>', views.list_idea_skills, name='idea_skill'),
    path('idea-materials/<int:material_id>', views.list_idea_materials, name='idea_material'),
    path('idea-worktype/<int:type_id>', views.list_idea_work_type, name='idea_work_type'),
]

skid/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path
from users.views import Credits, HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', HomePage.as_view(), name='home'),
    path('credits/', Credits.as_view(), name='credits'),
    path('directory/', include('directory.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
    path('summernote/', include('django_summernote.urls')),
]

# Early method for serving media. If this was bigger production use AWS buckets
# or similar.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('add-skill/', views.add_skill, name='add_skill'),
    path('add-material/', views.add_material, name='add_material'),
    path('add-work-type/', views.add_work_type, name='add_work_type'),
    path('<int:id>/', views.profile, name='profile'),
    path('<int:id>/edit/', views.edit_profile, name='edit_profile'),
    path('<int:id>/create-idea/', views.create_idea, name='create_idea'),
    path('<int:id>/edit-idea/<slug:slug>', views.edit_idea, name='edit_idea'),
    path('<int:id>/delete-idea/<slug:slug>', views.delete_idea, name='delete_idea'),
    path('<int:id>/view-ideas/', views.view_ideas, name='view_ideas'),
    
]

users/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.contrib.auth import get_user_model
from django_summernote.widgets import SummernoteWidget

from .models import *

User=get_user_model()

# Forms

class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')
 
    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True)
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)

    class Meta: 
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

class ProfileUpdateForm(forms.ModelForm):

    phone_number = forms.CharField(max_length=31, required=False)

    class Meta:
        model = Profile
        widgets = {
            'about': SummernoteWidget(),
        }

        fields = [
            'business_name',
            'email_public',
            'phone_number',
            'address',
            'city',
            'state_province',
            'zip_code',
            'country',
            'about',
            'skills',
            'materials',
            'type_of_work',
        ]

        labels = {
            'type_of_work': 'Type of Work',
        }

class IdeaForm(forms.ModelForm):

    class Meta:
        model = Idea
        widgets = {
            'author': forms.HiddenInput(),
            'slug': forms.HiddenInput(),
            'text': SummernoteWidget(),
        }

        fields = [
            'author',
            'title',
            'slug',
            'text',
            'skills',
            'materials',
            'type_of_work',
            'status'
        ]


class SkillForm(forms.ModelForm):
    skill = forms.CharField(required=False)

    class Meta:
        model = Skill
        fields= ['skill']

class MaterialForm(forms.ModelForm):
    material = forms.CharField(required=False)

    class Meta:
        model = Material
        fields= ['material']

class WorkTypeForm(forms.ModelForm):
    work_type = forms.CharField(required=False)

    class Meta:
        model = WorkType
        fields= ['work_type']

class CommentForm(forms.ModelForm):
    
    text = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 4}),
        required=False, label=False
    )

    class Meta:
        model = Comment
        widgets = {
            'idea': forms.HiddenInput(),
            'commenter': forms.HiddenInput()
        }
        
        fields = [
            'idea', 
            'commenter', 
            'text',
        ]

     

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.forms.models import model_to_dict
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from .forms import *
from .models import Profile

User=get_user_model()

# BASE VIEWS

class HomePage(TemplateView):
    """Class based view diplays the SKID homepage."""
    template_name = 'home.html'

class Credits(TemplateView):
    """Class based view diplays the credits page."""
    template_name = 'credits.html'

# USER APP VIEWS

@login_required()
def profile(request, id):
    """View function displays user profile."""
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            profile = Profile.objects.filter(user_id__id=id).first()
            context = {
                'profile': profile,
                'user': user,
            }
            return render(request, 'users/profile.html', context)

        raise Exception("users/views.py profile()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')
        

@login_required()
def edit_profile(request, id):
    """
    View function displays form to edit user profile. Dynamically
    prepopulates the form with previously saved data.
    """
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            if request.method == 'POST':
                user_form = UserUpdateForm(request.POST, instance=request.user)
                profile_form = ProfileUpdateForm(request.POST, instance=request.user.profile)

                if user_form.is_valid() and profile_form.is_valid():
                    user_form.save()
                    profile_form.save()
                    messages.success(request, "Profile updated successfully.")
                
                    return redirect('users:profile', id)

                else:
                    messages.warning(request, "Please correct the error below.")

            elif request.method == 'GET':
                # Queries user's profile for existing data
                profile_data = Profile.objects.filter(user_id__id=id).first()
                # Converts data into dict to be passed the initial field
                existing_data = model_to_dict(profile_data)

                user_form = UserUpdateForm(instance=request.user)
                profile_form = ProfileUpdateForm(instance=user, initial=existing_data)

                context = {
                    'user_form': user_form,
                    'profile_form': profile_form,
                }
                return render(request, 'users/edit_profile.html', context=context)

        raise Exception("users/views.py edit_profile()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def create_idea(request, id):
    """
    View function displays form for user to create Idea. Prepopulates 
    'author' field to connect Idea to user.
    """
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            if request.method == 'POST':
                form = IdeaForm(request.POST)
                if form.is_valid():
                    form.save()
                    messages.success(request, 'Idea created successfully.')
                    
                    return redirect('users:profile', id)

                else:
                    print(form.errors)

            elif request.method == 'GET':
                author_field = {'author': user}
                form = IdeaForm(instance=user, initial=author_field)
              
                context = {
                    'form': form
                }
                return render(request, 'users/create_idea.html', context=context)

        raise Exception("users/views.py create_idea()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def edit_idea(request, id, slug):
    """
    View function displays form to edit Idea. Dynamically prepopulates form
    with previously saved data.
    """
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            # Queries idea for existing data
            idea_data = Idea.objects.filter(slug=slug).first()

            if request.method == 'POST':
                form = IdeaForm(request.POST, instance=idea_data)
                if form.is_valid():
                    form.save()
                    messages.success(request, 'Idea edited successfully.')

                return redirect('users:view_ideas', id)

            elif request.method == 'GET':
                # Converts data into dict to be passed the initial field
                existing_data = model_to_dict(idea_data)
                idea_form = IdeaForm(instance=user, initial=existing_data)

                context = {
                    'idea_form': idea_form
                    }

                return render(request, 'users/edit_idea.html', context=context)
        
        raise Exception("users/views.py edit_idea()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def delete_idea(request, id, slug):
    """View function displays form to allow user to delete Idea."""
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            # Queries idea for existing data
            idea_data = Idea.objects.filter(slug=slug).first()

            if request.method == 'POST':
                idea_data.delete()
                messages.success(request, 'Idea deleted successfully.')

                return redirect('users:view_ideas', id)

            elif request.method == 'GET':
                context = {'idea_data': idea_data}
                
                return render(request, 'users/delete_idea.html', context)
        
        raise Exception("users/views.py delete_idea()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def view_ideas(request, id):
    """View function displays table of users Ideas."""
    try:
        userId = int(request.session["_auth_user_id"])
        user = User.objects.filter(id=userId).first()

        if user:
            ideas = Idea.objects.filter(author=user)
            context = {
                'ideas': ideas,
            }
            return render(request, 'users/view_ideas.html', context=context)

        raise Exception("users/views.py view_ideas()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def add_skill(request):
    """View function displays form for user to add Skill to table of skills."""
    try:
        skills = Skill.objects.all().order_by('skill')
        form = SkillForm(request.POST)

        if request.method == 'POST':
            if form.is_valid():
                instance = form.save(commit=False)
                if instance.skill == '':
                    messages.warning(request, 'Skill cannot be empty.')
                else:
                    instance.save()
                    messages.success(request, 'Skill added.')

            return redirect('users:add_skill')

        elif request.method == 'GET':
            context = {
                'skills': skills,
                'form': form,
            }

            return render(request, 'users/add_skill.html', context=context)
        
        raise Exception("users/views.py add_skill()")
    
    except Exception as err:
        # print("ERROR: ", str(err), file=sys.stderr)
        print("ERROR: ", str(err))
        context = {'error': str(err)}
        return render(request, 'error_page.html', context, content_type='text/html')


@login_required
def add_material(request):
    """
    View function displays form for user to add Material to table of materials.
    """
    try:
        materials = Material.objects.all().order_by('material')
        form = MaterialForm(request.POST)

        if request.method == 'POST':
            if form.is_valid():
                instance = form.save(commit=False)
                if instance.material == '':
                    messages.warning(request, 'Material cannot be empty.')
                else:
                    instance.save()
                    messages.success(request, 'Material added.')

            return redirect('users:add_material')

        elif request.method == 'GET':
            context = {
                'materials': materials,
                'form': form,
            }

            return render(request, 'users/add_material.html', context=context)

users/templates/users/add_material.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Add Materials</title>
{% endblock title %}


{% block navbar %}
    
{% endblock navbar %}
    

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="row justify-content-evenly">
        <div class="col-4">
            <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <input class="btn btn-success" type="submit" value="Add">
                <a class="btn btn-secondary btn-sm" onclick="closeWindow()">Return to Profile</a>
            </form>
        </div>

        <div class="col-8">
            <legend class="border-bottom mb-4">Available Materials:</legend>
            {% for material in materials %}
            <span class="badge rounded-pill text-bg-light">{{ material }}</span>            
            {% endfor %} 
        </div>
    </div>
</div>
   
{% endblock content %}
    

{% block footer %}
    
{% endblock footer %}


{% block scripts %}
    <script src="{% static 'js/new_window.js' %}"></script>
{% endblock scripts %}
    
    

users/templates/users/add_skill.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Add Skills</title>
{% endblock title %}


{% block navbar %}
    
{% endblock navbar %}
    

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="row justify-content-evenly">
        <div class="col-4">
            <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <input class="btn btn-success" type="submit" value="Add">
                <a class="btn btn-secondary btn-sm" onclick="closeWindow()">Return to Profile</a>
            </form>
        </div>

        <div class="col-8">
            <legend class="border-bottom mb-4">Available Skills:</legend>
            {% for skill in skills %}
            <span class="badge rounded-pill text-bg-light">{{ skill }}</span>            
            {% endfor %} 
        </div>
    </div>
</div>
   
{% endblock content %}
    

{% block footer %}
    
{% endblock footer %}


{% block scripts %}
    <script src="{% static 'js/new_window.js' %}"></script>
{% endblock scripts %}
    
    

users/templates/users/add_work_type.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Add Work Types</title>
{% endblock title %}


{% block navbar %}
    
{% endblock navbar %}
    

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="row justify-content-evenly">
        <div class="col-4">
            <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <input class="btn btn-success" type="submit" value="Add">
                <a class="btn btn-secondary btn-sm" onclick="closeWindow()">Return to Profile</a>
            </form>
        </div>

        <div class="col-8">
            <legend class="border-bottom mb-4">Available Work Types:</legend>
            {% for work_type in work_types %}
            <span class="badge rounded-pill text-bg-light">{{ work_type }}</span>            
            {% endfor %} 
        </div>
    </div>
</div>
   
{% endblock content %}
    

{% block footer %}
    
{% endblock footer %}


{% block scripts %}
    <script src="{% static 'js/new_window.js' %}"></script>
{% endblock scripts %}
    
    

users/templates/users/create_idea.html
{% extends 'base.html' %}


{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <legend class="border-bottom mb-4">Idea:</legend>
        <div class="container">
            <div class="row">
                <div class="col-md-4 mb-0">
                    {{ form.title | as_crispy_field }}
                </div>
                <div class="col-md-4 mb-0">
                    {{ form.author | as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 mb-0">
                    {{ form.text | as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 mb-0">
                    {{ form.skills | as_crispy_field }}
                </div>
                <div class="col-md-2 mb-0">
                    {{ form.materials| as_crispy_field }}
                </div>
                <div class="col-md-2 mb-2">
                    {{ form.type_of_work | as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 mb-2">
                    {{ form.status | as_crispy_field }}
                </div>
            </div>
        </div>
        <input class="btn btn-primary" style="margin-left: 10px;" type="submit" value="Save">
        <a class="btn btn-secondary" href="{% url 'users:profile' user.id %}">Cancel</a>
    </form>
</div>

{% endblock content %}
    

users/templates/users/delete_idea.html
{% extends 'base.html' %} 

{% block content %}

<div class="container">
  <legend class="border-bottom mb-4">Delete Idea:</legend>
  <div class="container">
    <form method="POST">
      {% csrf_token %}
      <p>Are you sure that you want to delete <strong>"{{ idea_data.title }}"</strong>?</p>
      <div>
        <button class="btn btn-danger" type="submit">Delete</button>
        <a class="btn btn-secondary" href="{% url 'users:view_ideas' user.id %}">Cancel</a>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

users/templates/users/edit_idea.html
{% extends 'base.html' %}


{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <legend class="border-bottom mb-4">Idea:</legend>
        <div class="container">
            <div class="row">
                <div class="col-md-4 mb-0">
                    {{ idea_form.title | as_crispy_field }}
                </div>
                <div class="col-md-4 mb-0">
                    {{ idea_form.author | as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 mb-0">
                    {{ idea_form.text | as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 mb-0">
                    {{ idea_form.skills | as_crispy_field }}
                </div>
                <div class="col-md-2 mb-0">
                    {{ idea_form.materials| as_crispy_field }}
                </div>
                <div class="col-md-2 mb-2">
                    {{ idea_form.type_of_work | as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 mb-2">
                    {{ idea_form.status | as_crispy_field }}
                </div>
            </div>
        </div>
        <input class="btn btn-primary" style="margin-left: 10px;" type="submit" value="Save">
        <a class="btn btn-secondary" href="{% url 'users:profile' user.id %}">Cancel</a>
    </form>
</div>

{% endblock content %}
    

users/templates/users/profile.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8 order-1">

            <legend class="border-bottom mb-4">Account Information:</legend>
                <div>
                    <ul style="list-style-type:none;">
                        <li><strong>Username:</strong> {{ user.username }}</li>
                        <li><strong>First Name:</strong> {{ user.first_name }}</li>
                        <li><strong>Last Name:</strong>  {{ user.last_name }}</li>
                        <li><strong>Account Email:</strong> {{ user.email }}</li>
                    </ul>
                </div>    
            
            <legend class="border-bottom mb-4">Profile Information:</legend>
                <div>
                    <ul style="list-style-type:none;">
                        <li><strong>Business Name:</strong> {{ profile.business_name }}</li>
                        <li><strong>Public Email:</strong> {{ profile.email_public }}</li>
                        <li><strong>Phone:</strong> {{ profile.phone_number }}</li>
                        <li>
                            <strong>Address:</strong><br>
                            {{ profile.address }}<br>
                            {{ profile.city }}<br>
                            {{ profile.state_province }}<br>
                            {{ profile.zip_code }}
                            {{ profile.country }}<br>
                        </li>
                        <br>
                        <li><strong>About:</strong> {{ profile.about | safe }}</li>
                        <br>
                        <li>
                            <strong>Skills:</strong>
                            {% for skill in profile.skills.all %} 
                            <span class="badge rounded-pill text-bg-light">{{ skill }}</span>
                            {% endfor %}
                        </li>   
                        <li>
                            <strong>Materials:</strong>
                            {% for material in profile.materials.all %}
                            <span class="badge rounded-pill text-bg-light">{{ material }}</span>
                            {% endfor %}
                        </li>
                        <li>
                            <strong>Type of Work:</strong>
                            {% for type in profile.type_of_work.all %}
                            <span class="badge rounded-pill text-bg-light">{{ type }}</span>
                            {% endfor %}
                        </li>
                    </ul>
                </div>
        </div>

        <!-- Sidebar -->
        <div class="col-4 order-2">
            <div class="sidenav">
                <a id="id_edit_info" class="nav-link btn btn-secondary" href="{% url 'users:edit_profile' user.id %}">Edit Information</a>
                <a id="id_create_idea" class="nav-link btn btn-secondary" href="{% url 'users:create_idea' user.id %}">Create Idea</a>
                <a id="id_view_ideas"  class="nav-link btn btn-secondary" href="{% url 'users:view_ideas' user.id %}">View Ideas</a>
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}

users/templates/users/view_ideas.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <legend>My Ideas:</legend>
            <div>
                <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Title</th>
                        <th scope="col">Published</th>
                        <th scope="col">Updated</th>
                        <th scope="col">Status</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for idea in ideas %}
                        <tr>
                            <th scope="row">
                                <a href="{% url 'directory:idea_detail' idea.slug %}">{{ idea.title }}</a>
                            </th>
                            <td>{{ idea.published }}</td>
                            <td>{{ idea.updated }}</td>

                            {% if idea.status == 'p' %}
                                <td>Published</td>
                            {% elif idea.status == 'd' %}
                                <td>Draft</td>
                            {% endif %}

                            <td><a class="btn btn-primary btn-sm" href="{% url 'users:edit_idea' idea.author.id idea.slug %}">Edit</a></td>
                            <td><a class="btn btn-danger btn-sm" href="{% url 'users:delete_idea' idea.author.id idea.slug %}">Delete</a></td>    
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    </div>
{% endblock content %}
    